---
- name: Check R version installed
  command: "R --version"
  register: version_r
  changed_when: false
  failed_when: false

- block:
    - name: Install system dependencies
      apt:
        name: "{{ lookup('file', 'package_list_compile_r.txt').splitlines() }}"
        state: present

    - name: Download R source
      unarchive:
        src: "https://cran.rstudio.com/src/base/R-{{ r_version\n
        | regex_search('^\\d', multiline=True)\n
        | trim }}/R-{{ r_version }}.tar.gz"
        remote_src: true
        dest: /usr/local/src
        creates: "/usr/local/src/R-{{ r_version }}"

    - name: Configure R compilation
      command:
        cmd: ./configure --enable-R-shlib --enable-memory-profiling --with-blas --with-lapack
        chdir: "/usr/local/src/R-{{ r_version }}"
        creates: "/usr/local/src/R-{{ r_version }}/Makeconf"

    - name: Compile R
      make:
        chdir: "/usr/local/src/R-{{ r_version }}"

    - name: Install R
      make:
        chdir: "/usr/local/src/R-{{ r_version }}"
        target: install

    - name: Remove installation files
      file:
        path: "/usr/local/src/R-{{ r_version }}"
        state: absent
  when:
    - "r_version|string not in version_r|string"
    - use_r4pi == false
    - use_rig == false

- block:
    - name: Add R4Pi repo key
      get_url:
        url: https://pkgs.r4pi.org/dl/r4pi.asc
        dest: /etc/apt/trusted.gpg.d/r4pi.asc

    - name: Add R4Pi apt source
      apt_repository:
        repo: "deb http://debs.r4pi.org/ bullseye main"
        state: present

    - name: Install R4Pi
      apt:
        name:
          - libcurl4-openssl-dev
          - libssl-dev
          - libabsl-dev
          - libjemalloc-dev
          - r4pi
        update_cache: true
        state: present
  when:
    - use_r4pi
    - use_rig == false
    - ansible_distribution == 'Debian'

- block:
    - name: Install rig
      unarchive:
        src: https://github.com/r-lib/rig/releases/download/latest/rig-linux-arm64-latest.tar.gz
        remote_src: true
        dest: /usr/local/
        creates: /usr/local/bin/rig

    - name: Install R with rig
      command:
        cmd: "rig add {{r_version}} --without-cran-mirror"
        creates: "/opt/R/{{r_version}}/bin/R"

    - name: Set default R version
      command:
        cmd: "rig default {{r_version}}"
      changed_when: false
  when:
    - "r_version|string not in version_r|string"
    - use_rig
    - use_r4pi == false
