---
- name: Get current RStudio version
  command: "rstudio-server version"
  register: version_rstudio
  changed_when: false
  failed_when: false

- block:
  - name: Download rstudio-server daily build for Ubuntu
    get_url:
      url: "https://s3.amazonaws.com/rstudio-ide-build/server/{{ ansible_distribution_release }}/arm64/rstudio-server-{{ rstudio_version.replace('+', '-') }}-arm64.deb"
      dest: ~/rstudio-server-{{ rstudio_version }}-arm64.deb
    when: ansible_distribution == 'Ubuntu'

  - name: Download rstudio-server daily build compatible with Raspberry Pi OS
    get_url:
      url: "https://s3.amazonaws.com/rstudio-ide-build/server/bionic/arm64/rstudio-server-{{ rstudio_version.replace('+', '-') }}-arm64.deb"
      dest: ~/rstudio-server-{{ rstudio_version }}-arm64.deb
    when: ansible_distribution == 'Debian'

  - name: Install rstudio-server
    command:
      cmd: gdebi ~/rstudio-server-{{ rstudio_version }}-arm64.deb -n

  - name: Remove installer
    file:
      path: "~/rstudio-server-{{ rstudio_version }}-arm64.deb"
      state: absent

  - name: Make sure rstudio-server is started
    service:
      name: rstudio-server
      enabled: true
      state: started
  when: "rstudio_version | string not in version_rstudio|string"
