---
- name: Set timeout
  lineinfile:
    path: /etc/rstudio/rserver.conf
    line: auth-timeout-minutes=240
    state: present
    create: true

- name: Allow access to /srv/shiny-server/ folder
  lineinfile:
    path: /etc/rstudio/rsession.conf
    line: directory-view-allow-list=/srv/shiny-server
    state: present
    create: true

- name: Install pandoc system library
  apt:
    name:
      - pandoc
    state: present

- name: Check if default_site file exists
  stat:
    path: /etc/nginx/sites-enabled/default_site
  register: nginx_file_check

- block:
  - name: Add map to Nginx config file
    blockinfile:
      path: /etc/nginx/sites-enabled/default_site
      block: |2
        map $http_upgrade $connection_upgrade {
            default upgrade;
            ''      close;
        }
      marker: "# <!-- {mark} ANSIBLE MANAGED BLOCK #1 -->"
      insertbefore: BOF
    notify: restart_nginx

  - name: Configure Nginx as reverse proxy for RStudio Server
    blockinfile:
      path: /etc/nginx/sites-enabled/default_site
      block: |2
                location /rstudio/ {
                   # Needed only for prefix of /rstudio
                   rewrite ^/rstudio/(.*)$ /$1 break;

                   # Use http here when ssl-enabled=0 is set in rserver.conf
                   proxy_pass http://localhost:8787;
                   proxy_http_version 1.1;

                   proxy_set_header Upgrade $http_upgrade;
                   proxy_set_header Connection $connection_upgrade;

                   # Optionally, use an explicit hostname and omit the port if using 80/443
                   proxy_set_header Host $host:$server_port;

                   # Not needed if there's no prefix or www-root-path is set in rserver.conf
                   proxy_set_header X-RStudio-Root-Path /rstudio;

                   proxy_read_timeout 20d;
                }
      marker: "# <!-- {mark} ANSIBLE MANAGED BLOCK #3 -->"
      insertbefore: "location / {"
    notify: restart_nginx

  - name: Delay nginx start to give rstudio-server time to load
    lineinfile:
      path: /etc/systemd/system/multi-user.target.wants/nginx.service
      regexp: '^After=network'
      line: 'After=network-online.target nss-lookup.target'
      state: present
    notify: restart_nginx
    when: ansible_distribution == 'Debian'

  - name: Restart daemon
    systemd:
      daemon_reload: true
    changed_when: false
    when: ansible_distribution == 'Debian'

  when: nginx_file_check.stat.exists
