---
- name: Create rstudio-server user
  user:
    name: rstudio-server
    system: true

- name: Create folders for Rstudio server
  file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
    recurse: true
  with_items:
    - path: /var/run/rstudio-server
      mode: "0777"
    - path: /var/lock/rstudio-server
      mode: "0755"
    - path: /var/log/rstudio-server
      mode: "0755"
    - path: /var/lib/rstudio-server
      mode: "0755"
    - path: /var/lib/rstudio-server
      mode: "0755"

- name: Install pandoc library
  apt:
    name:
      - pandoc
      - pandoc-citeproc
    state: present

- name: Create symlinks for the system version of pandoc
  file:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    state: link
    force: true
  with_items:
    - path: /usr/local/bin/pandoc/pandoc
      src: /usr/bin/pandoc
    - path: /usr/local/bin/pandoc/pandoc-citeproc
      src: /usr/bin/pandoc-citeproc

- name: Check if default_site file exists
  stat:
    path: /etc/nginx/sites-enabled/default_site
  register: nginx_file_check

- block:
  - name: Add map to Nginx config file
    blockinfile:
      path: /etc/nginx/sites-enabled/default_site
      block: |
        map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
            }
      marker: "# <!-- {mark} ANSIBLE MANAGED BLOCK #1 -->"
      insertbefore: BOF
    notify: restart_nginx

  - name: Configure Nginx as reverse proxy for RStudio Server
    blockinfile:
      path: /etc/nginx/sites-enabled/default_site
      block: |2
                rewrite ^/rstudio$ $scheme://$http_host/rstudio/ permanent;

                location /rstudio/ {
                        rewrite ^/rstudio/(.*)$ /$1 break;
                        proxy_pass http://localhost:8787;
                        proxy_redirect http://localhost:8787/ $scheme://$http_host/rstudio/;
                        proxy_http_version 1.1;
                        proxy_set_header Upgrade $http_upgrade;
                        proxy_set_header Connection $connection_upgrade;
                        proxy_read_timeout 20d;
                }
      marker: "# <!-- {mark} ANSIBLE MANAGED BLOCK #3 -->"
      insertbefore: "location / {"
    notify: restart_nginx
  when: nginx_file_check.stat.exists
