---
- name: Update apt repo and cache
  apt:
    update_cache: true
    cache_valid_time: 3600

- name: Upgrade packages
  apt:
    upgrade: dist
    autoremove: true
    autoclean: true
    install_recommends: true

- name: Check if a reboot is requiered
  stat:
    path: /var/run/reboot-required
  notify: reboot_raspberry
