---
- name: Check if swap file exists
  stat:
    path: "{{ swap_file_path }}"
  register: swap_file_check

- name: Create swap file
  command: fallocate -l {{ swap_file_size }} {{ swap_file_path }}
  when: not swap_file_check.stat.exists

- name: Change swap file permissions
  file:
    path: "{{ swap_file_path }}"
    owner: root
    group: root
    mode: '0600'

- name: Format swap file
  command: "mkswap {{swap_file_path}}"
  when: not swap_file_check.stat.exists

- name: Write swap entry in fstab
  mount:
    name: swap
    src: "{{ swap_file_path }}"
    fstype: swap
    opts: sw
    passno: '0'
    dump: '0'
    state: present

- name: Turn on swap
  command: swapon -a
  when: not swap_file_check.stat.exists

- name: Set swappiness
  sysctl:
    name: vm.swappiness
    value: "{{ swappiness }}"
