---
# System Configurations ########################################################

# Swap parameters
swap_file_path: /var/swap.1
# Use any of the following suffixes
# c=1
# w=2
# b=512
# kB=1000
# K=1024
# MB=1000*1000
# M=1024*1024
# xM=M
# GB=1000*1000*1000
# G=1024*1024*1024
swap_file_size: 3GB
swappiness: '10'

# Disable WiFi interface?
disable_wifi: false

# Security Configurations ######################################################

# Ports to open
exposed_ports:
  - { rule: 'allow', port: 22, proto: 'tcp' }   # ssh
  - { rule: 'allow', port: 22, proto: 'udp' }
  - { rule: 'allow', port: 80, proto: 'tcp' }   # http
  - { rule: 'allow', port: 5432, proto: 'tcp' }   # Postgresql
  - { rule: 'allow', port: 5432, proto: 'udp' }

# Notification email for fail2ban
send_email: true
fail2ban_email: your_email@something.com

# Password for the main PostgreSQL user
postgres_password: 'very_secure_password'

# Access rules for Postgresql
postgresql_rules:
  - { contype: local, users: all, address: samehost, method: trust }
  - { contype: local, users: postgres, address: samehost, method: trust }
  - { contype: host, users: all, address: "{{ ansible_default_ipv4.network }}/24", method: trust }
  - { contype: host, users: all, address: 0.0.0.0/0, method: password }
  - { contype: host, users: all, address: 127.0.0.1/32, method: md5 }
  - { contype: host, users: all, address: '::1/128', method: trust }

# Main Software Versions #######################################################

# R version to install
r_version: '4.1.2'

# Shiny-server version to install
shiny_server_version: 'v1.5.17.973'

# RStudio version to install
rstudio_version: 'v2021.09.2+382'
