---
- name: Check shiny-server version installed
  command: "shiny-server --version"
  register: version_shiny
  changed_when: false
  failed_when: false

- block:
  - name: Clone shiny-server repository
    git:
      repo: "https://github.com/rstudio/shiny-server.git"
      clone: true
      dest: "shiny-server"
      version: "{{ shiny_server_version }}"
      accept_hostkey: true
      force: true
      depth: 1

  - name: Create 'tmp' and 'build' folders
    file:
      path: "{{ item }}"
      state: directory
    with_items:
      - "shiny-server/tmp"
      - "shiny-server/build"

  - name: Execute install_node.sh script
    shell:
      cmd: ./external/node/install-node.sh
      chdir: shiny-server

  - name: Prepare the make step with cmake
    shell:
      cmd: |
        PYTHON=`which python3`
        DIR=`pwd`
        PATH=$DIR/../bin:$PATH
        cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DPYTHON="$PYTHON" ../
      chdir: "shiny-server/tmp"
      creates: cmake_install.cmake

  - name: Compile Shiny
    make:
      chdir: "shiny-server/tmp"

  - name: Install and rebuild npm dependencies
    shell:
      cmd: |
        DIR=`pwd`
        PATH=$DIR/../bin:$PATH
        PYTHON=`which python3`
        (cd .. && ./bin/npm ci --omit-dev --python="${PYTHON}") 
      chdir: shiny-server/tmp

  - name: Install shiny-server
    make:
      chdir: "shiny-server/tmp"
      target: install

  - name: Make sure /etc/shiny-server folder exist
    file:
      path: /etc/shiny-server/
      state: directory

  - name: Get current locale configuration
    command: localectl status
    register: locale_status
    changed_when: false

  - name: Parse 'LANG' from current locale and language configuration
    set_fact:
      locale_lang: "{{ locale_status.stdout | regex_search('LANG=([^\n]+)', '\\1') | first }}"

  - name: Create systemd service file
    template:
      src: shiny-server-service.j2
      dest: /etc/systemd/system/shiny-server.service
      owner: root
      group: root
      mode: '0644'

  - name: Create log rotate config for shiny-server
    copy:
      src: shiny-server
      dest: /etc/logrotate.d/shiny-server
      owner: root
      mode: "0644"
      force: false

  - name: Install default config file
    copy:
      src: shiny-server/config/default.config
      dest: /etc/shiny-server/shiny-server.conf
      remote_src: true
      owner: root
      mode: "0644"

  - name: Create symlink for shiny-server
    file:
      path: /usr/bin/shiny-server
      src: /usr/local/shiny-server/bin/shiny-server
      state: link
      owner: root

  - name: Make sure shiny-server is started
    systemd:
      daemon_reload: true
      name: shiny-server
      enabled: true
      state: started

  - name: Remove installation files
    file:
      path: shiny-server/
      state: absent

  when: "shiny_server_version |\n
      regex_search('^v\\d\\.\\d+\\.\\d+', multiline=True) |\n
      trim | string not in version_shiny | string"
