---
- name: Install PostgreSQL libraries
  apt:
    name:
      - libpq-dev
      - postgresql
      - postgresql-client
      - postgresql-client-common
      - python3-psycopg2
    state: present

- name: "Update list of installed packages"
  package_facts:
    manager: "apt"

- name: Get PostgreSQL major version
  set_fact:
    postgresql_major: "{{ ansible_facts.packages['postgresql'][0].version\n
    | regex_search('^\\d{2}', multiline=True) | trim }}"

- name: Configure PostgreSQL access rules
  postgresql_pg_hba:
    dest: /etc/postgresql/{{ postgresql_major }}/main/pg_hba.conf
    contype: "{{ item.contype }}"
    users: "{{ item.users }}"
    address: "{{ item.address }}"
    databases: all
    method: "{{ item.method }}"
  with_items: "{{ postgresql_rules }}"
  notify:
    - restart_postgresql

- name: Force restart_postgresql handler
  meta: flush_handlers

- name: Configure PostgreSQL options
  postgresql_set:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  with_items:
    - name: listen_addresses
      value: '*'
    - name: password_encryption
      value: 'scram-sha-256'
  notify: restart_postgresql

- name: Force restart_postgresql handler
  meta: flush_handlers

- name: Create the main users
  postgresql_user:
    name: "{{ item.name }}"
    password: "{{ postgres_password }}"
    state: present
  with_items:
    - name: "{{ ansible_user }}"
    - name: postgres

- name: Create the main database
  postgresql_db:
    name: "{{ ansible_user }}"
    owner: "{{ ansible_user }}"
    state: present
