---
- name: Install Nginx
  apt:
    name:
      - nginx
    state: latest

- name: Create html directory
  file:
    path: /var/www/html
    owner: "{{ ansible_user }}"
    group: www-data
    mode: '0777'
    state: directory

- name: Remove default sites file
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Create Nginx sites configuration file
  template:
    src: default_site.j2
    dest: /etc/nginx/sites-enabled/default_site
    owner: root
    group: root
    mode: '0644'
    force: false
  notify: restart_nginx
